image: alpine:latest

before_script:
  - apk update
  - apk add python build-essential autoconf libtool libprotobuf-dev protobuf-compiler libzmq3-dev libsqlite3-dev

build:
  stage: build
  tags:
    - shared
  script:
    - ./configure
    - make
